/*
  # Bulk Import Titles from Payment Upload

  1. New Titles
    - 140 unique movie titles from payment records
    - All set as Type: Movie, Status: Approved
    - Ready for filmmaker assignment and payment matching

  2. Security
    - All titles inherit existing RLS policies
    - Duplicates are automatically skipped using ON CONFLICT DO NOTHING

  3. Notes
    - Revenue fields start at 0 and will update when payments are assigned
    - Filmmakers can be assigned later via admin dashboard
*/

INSERT INTO public.content (
  title_name,
  content_type,
  status,
  revenue_total,
  distribution_fee,
  expenses_total,
  net_revenue
) VALUES
  ('THE RED RESURRECTION', 'movie', 'approved', 0, 0, 0, 0),
  ('Good Grief', 'movie', 'approved', 0, 0, 0, 0),
  ('Bury Me Twice', 'movie', 'approved', 0, 0, 0, 0),
  ('The Secrets of Jonathan Sperry', 'movie', 'approved', 0, 0, 0, 0),
  ('A Horse Called Bear', 'movie', 'approved', 0, 0, 0, 0),
  ('Hidden Secrets', 'movie', 'approved', 0, 0, 0, 0),
  ('Hometown Legend', 'movie', 'approved', 0, 0, 0, 0),
  ('Clancy', 'movie', 'approved', 0, 0, 0, 0),
  ('My Daddy is in Heaven', 'movie', 'approved', 0, 0, 0, 0),
  ('Mr. Troop Mom', 'movie', 'approved', 0, 0, 0, 0),
  ('Like a Country Song', 'movie', 'approved', 0, 0, 0, 0),
  ('An Interview with God', 'movie', 'approved', 0, 0, 0, 0),
  ('Road to Victory', 'movie', 'approved', 0, 0, 0, 0),
  ('The Least of These', 'movie', 'approved', 0, 0, 0, 0),
  ('The Frontier Boys', 'movie', 'approved', 0, 0, 0, 0),
  ('Hearts of Spring', 'movie', 'approved', 0, 0, 0, 0),
  ('Marriage Retreat', 'movie', 'approved', 0, 0, 0, 0),
  ('Homecoming Christmas', 'movie', 'approved', 0, 0, 0, 0),
  ('The Mulligan', 'movie', 'approved', 0, 0, 0, 0),
  ('Love Finds You in Charm', 'movie', 'approved', 0, 0, 0, 0),
  ('Love Finds You in Valentine', 'movie', 'approved', 0, 0, 0, 0),
  ('Not My Life', 'movie', 'approved', 0, 0, 0, 0),
  ('Suing the Devil', 'movie', 'approved', 0, 0, 0, 0),
  ('Amazing Love', 'movie', 'approved', 0, 0, 0, 0),
  ('Love Finds You in Sugarcreek', 'movie', 'approved', 0, 0, 0, 0),
  ('Letters to God', 'movie', 'approved', 0, 0, 0, 0),
  ('Alleged', 'movie', 'approved', 0, 0, 0, 0),
  ('The Stream', 'movie', 'approved', 0, 0, 0, 0),
  ('After the Harvest', 'movie', 'approved', 0, 0, 0, 0),
  ('Nora Roberts - Tribute', 'movie', 'approved', 0, 0, 0, 0),
  ('Nora Roberts Angels Fall', 'movie', 'approved', 0, 0, 0, 0),
  ('Sweet Laurel', 'movie', 'approved', 0, 0, 0, 0),
  ('Second Chances', 'movie', 'approved', 0, 0, 0, 0),
  ('Undercover Bridesmaid', 'movie', 'approved', 0, 0, 0, 0),
  ('Making the Rules', 'movie', 'approved', 0, 0, 0, 0),
  ('A Cowgirl Story', 'movie', 'approved', 0, 0, 0, 0),
  ('Dater''s Handbook', 'movie', 'approved', 0, 0, 0, 0),
  ('Love Struck Café', 'movie', 'approved', 0, 0, 0, 0),
  ('Wedding March', 'movie', 'approved', 0, 0, 0, 0),
  ('Love on the Menu', 'movie', 'approved', 0, 0, 0, 0),
  ('The Perfect Bride', 'movie', 'approved', 0, 0, 0, 0),
  ('Campfire Kiss', 'movie', 'approved', 0, 0, 0, 0),
  ('Love at First Glance', 'movie', 'approved', 0, 0, 0, 0),
  ('On the Twelfth Day of Christmas', 'movie', 'approved', 0, 0, 0, 0),
  ('Christmas Encore', 'movie', 'approved', 0, 0, 0, 0),
  ('A Bride for Christmas', 'movie', 'approved', 0, 0, 0, 0),
  ('Season for Love', 'movie', 'approved', 0, 0, 0, 0),
  ('Christmas Getaway', 'movie', 'approved', 0, 0, 0, 0),
  ('Appetite for Love', 'movie', 'approved', 0, 0, 0, 0),
  ('June in January', 'movie', 'approved', 0, 0, 0, 0),
  ('All of My Heart', 'movie', 'approved', 0, 0, 0, 0),
  ('Summer in the City', 'movie', 'approved', 0, 0, 0, 0),
  ('Unleashing Mr. Darcy', 'movie', 'approved', 0, 0, 0, 0),
  ('Love on a Limb', 'movie', 'approved', 0, 0, 0, 0),
  ('All Things Valentine', 'movie', 'approved', 0, 0, 0, 0),
  ('Christmas Under Wraps', 'movie', 'approved', 0, 0, 0, 0),
  ('My Christmas Dream', 'movie', 'approved', 0, 0, 0, 0),
  ('A Country Wedding', 'movie', 'approved', 0, 0, 0, 0),
  ('Window Wonderland', 'movie', 'approved', 0, 0, 0, 0),
  ('Wedding March 2', 'movie', 'approved', 0, 0, 0, 0),
  ('Destination Wedding', 'movie', 'approved', 0, 0, 0, 0),
  ('Love Blossoms', 'movie', 'approved', 0, 0, 0, 0),
  ('Moonlight in Vermont', 'movie', 'approved', 0, 0, 0, 0),
  ('Christmas List', 'movie', 'approved', 0, 0, 0, 0),
  ('The Wishing Tree', 'movie', 'approved', 0, 0, 0, 0),
  ('Marrying Mr. Darcy', 'movie', 'approved', 0, 0, 0, 0),
  ('Love at the Shore', 'movie', 'approved', 0, 0, 0, 0),
  ('Picture Perfect Mysteries', 'movie', 'approved', 0, 0, 0, 0),
  ('The Convenient Groom', 'movie', 'approved', 0, 0, 0, 0),
  ('Love Takes Flight', 'movie', 'approved', 0, 0, 0, 0),
  ('Love by the Book', 'movie', 'approved', 0, 0, 0, 0),
  ('Follow Your Heart', 'movie', 'approved', 0, 0, 0, 0),
  ('A Taste of Summer', 'movie', 'approved', 0, 0, 0, 0),
  ('A Royal Winter', 'movie', 'approved', 0, 0, 0, 0),
  ('A Christmas Detour', 'movie', 'approved', 0, 0, 0, 0),
  ('Christmas in Homestead', 'movie', 'approved', 0, 0, 0, 0),
  ('A Wish for Christmas', 'movie', 'approved', 0, 0, 0, 0),
  ('Love in Design', 'movie', 'approved', 0, 0, 0, 0),
  ('Just My Type', 'movie', 'approved', 0, 0, 0, 0),
  ('The Christmas Cottage', 'movie', 'approved', 0, 0, 0, 0),
  ('Angel of Christmas', 'movie', 'approved', 0, 0, 0, 0),
  ('Christmas in Angel Falls', 'movie', 'approved', 0, 0, 0, 0),
  ('Sweet Mountain Christmas', 'movie', 'approved', 0, 0, 0, 0),
  ('With Love, Christmas', 'movie', 'approved', 0, 0, 0, 0),
  ('Christmas Next Door', 'movie', 'approved', 0, 0, 0, 0),
  ('My Christmas Love', 'movie', 'approved', 0, 0, 0, 0),
  ('Christmas at Pemberley Manor', 'movie', 'approved', 0, 0, 0, 0),
  ('Royal Hearts', 'movie', 'approved', 0, 0, 0, 0),
  ('Love, Once and Always', 'movie', 'approved', 0, 0, 0, 0),
  ('Surprised by Love', 'movie', 'approved', 0, 0, 0, 0),
  ('A Princess for Christmas', 'movie', 'approved', 0, 0, 0, 0),
  ('Crown for Christmas', 'movie', 'approved', 0, 0, 0, 0),
  ('A Royal Christmas', 'movie', 'approved', 0, 0, 0, 0),
  ('Wedding Bells', 'movie', 'approved', 0, 0, 0, 0),
  ('A December Bride', 'movie', 'approved', 0, 0, 0, 0),
  ('My Summer Prince', 'movie', 'approved', 0, 0, 0, 0),
  ('The Bridge - Part 2', 'movie', 'approved', 0, 0, 0, 0),
  ('The Bridge', 'movie', 'approved', 0, 0, 0, 0),
  ('Karen Kingsbury''s Maggie''s Christmas Miracle', 'movie', 'approved', 0, 0, 0, 0),
  ('October Baby', 'movie', 'approved', 0, 0, 0, 0),
  ('Moms'' Night Out', 'movie', 'approved', 0, 0, 0, 0),
  ('Do You Believe?', 'movie', 'approved', 0, 0, 0, 0),
  ('God''s Not Dead', 'movie', 'approved', 0, 0, 0, 0),
  ('Forever My Girl', 'movie', 'approved', 0, 0, 0, 0),
  ('Selfie Dad', 'movie', 'approved', 0, 0, 0, 0),
  ('Summer of ''67', 'movie', 'approved', 0, 0, 0, 0),
  ('Revelation Road', 'movie', 'approved', 0, 0, 0, 0),
  ('Revelation Road 2', 'movie', 'approved', 0, 0, 0, 0),
  ('Revelation Road 3', 'movie', 'approved', 0, 0, 0, 0),
  ('Revelation Road - Beginning of the End', 'movie', 'approved', 0, 0, 0, 0),
  ('What Would Jesus Do?', 'movie', 'approved', 0, 0, 0, 0),
  ('In His Steps', 'movie', 'approved', 0, 0, 0, 0),
  ('Miracle Maker', 'movie', 'approved', 0, 0, 0, 0),
  ('Extraordinary', 'movie', 'approved', 0, 0, 0, 0),
  ('Christmas Child', 'movie', 'approved', 0, 0, 0, 0),
  ('Crazy Enough', 'movie', 'approved', 0, 0, 0, 0),
  ('Finding Normal', 'movie', 'approved', 0, 0, 0, 0),
  ('Champion', 'movie', 'approved', 0, 0, 0, 0),
  ('Indivisible', 'movie', 'approved', 0, 0, 0, 0),
  ('The Case for Christ', 'movie', 'approved', 0, 0, 0, 0),
  ('The Warrant', 'movie', 'approved', 0, 0, 0, 0),
  ('Woodlawn', 'movie', 'approved', 0, 0, 0, 0),
  ('Same Kind of Different as Me', 'movie', 'approved', 0, 0, 0, 0),
  ('I Can Only Imagine', 'movie', 'approved', 0, 0, 0, 0),
  ('Like Arrows', 'movie', 'approved', 0, 0, 0, 0),
  ('God''s Compass', 'movie', 'approved', 0, 0, 0, 0),
  ('I''m Not Ashamed', 'movie', 'approved', 0, 0, 0, 0),
  ('Beautifully Broken', 'movie', 'approved', 0, 0, 0, 0),
  ('Unplanned', 'movie', 'approved', 0, 0, 0, 0),
  ('Run the Race', 'movie', 'approved', 0, 0, 0, 0),
  ('Midway to Heaven', 'movie', 'approved', 0, 0, 0, 0),
  ('To Save a Life', 'movie', 'approved', 0, 0, 0, 0),
  ('Courageous', 'movie', 'approved', 0, 0, 0, 0),
  ('Facing the Giants', 'movie', 'approved', 0, 0, 0, 0),
  ('Flywheel', 'movie', 'approved', 0, 0, 0, 0),
  ('Fireproof', 'movie', 'approved', 0, 0, 0, 0),
  ('War Room', 'movie', 'approved', 0, 0, 0, 0),
  ('Overcomer', 'movie', 'approved', 0, 0, 0, 0),
  ('Show Me the Father', 'movie', 'approved', 0, 0, 0, 0),
  ('The Forge', 'movie', 'approved', 0, 0, 0, 0)
ON CONFLICT (title_name) DO NOTHING;
